Relax transfer bytes check in test_remote.test_fetch
On Fedora 40, this test fails with:

__________________________________ test_fetch __________________________________
emptyrepo = pygit2.Repository('/tmp/pytest-of-mockbuild/pytest-0/test_fetch0/emp
tyrepo/.git/')
    def test_fetch(emptyrepo):
        remote = emptyrepo.remotes[0]
        stats = remote.fetch()
>       assert stats.received_bytes == REMOTE_REPO_BYTES
E       assert 2760 == 2758
E        +  where 2760 = <pygit2.remote.TransferProgress object at 0xf60a7db0>.received_bytes
test/test_remote.py:218: AssertionError

Probably due to zlib-ng/zlib differences.