error: replace `GIT_REVWALKOVER` with `GIT_ITEROVER`.
This catches up with changes in libgit2:

  commit f335ecd6e126aa9dea28786522c0e6ce71596e91
  Author: Russell Belfer <rb@github.com>
  Date:   Thu Aug 30 14:24:16 2012 -0700